version: '3'
 
services:
  node:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=ynov
      - DATABASE_PASSWORD=ynov
      - DATABASE_NAME=appdb
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=ynov
      - MYSQL_PASSWORD=ynov
      - MYSQL_ROOT_PASSWORD=ynov
    volumes:
    - db_data:/var/lib/mysql

volumes:
  db_data:
